name: "This is a test continuous integration & deployment for a calculator"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: "Hola Raymundo"
        run: |
          echo "Hello world"
          echo "hello world" > hello_world.txt

      - name: "Files"
        run: ls
