name: "This is a test continuous integration & deployment for a calculator"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout files"
        uses: actions/checkout@v4
      - name: "Install packages"
        run: |
          python -m pip install pytest
          python -m pip install ruff
      - name: "Linting"
        run: make lint 
      - name: "Formating"
        run:  make format
      - name: "Sorting"
        run: make sort 
      - name: "Testing"
        run: make test


