name: "This is a test continuous integration & deployment for a calculator"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout files"
        uses: actions/checkout@v4
      - name: "Install packages"
        run: |
        python -m pip install pytest
        python -m pip install ruff
      - name: "Linting"
        run: |
        ruff check src/
        ruff check calculator.py
      - name: "Formating"
        run: |
        ruff format --check src/
        ruff format --check calculator.py
      - name: "Sorting"
        run: |
        ruff --select I src/
        ruff --select I calculator.py
      - name: "Testing"
        run: make test


