name: "This is a test continuous integration & deployment for a calculator"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout files"
        uses: actions/checkout@v4
      - name: "Install packages"
        run: |
          python -m pip install pytest
          python -m pip install ruff
      - name: "Linting"
        run: make lint 
      - name: "Formating"
        run:  make format
      - name: "Sorting"
        run: make sort 
      - name: "Testing"
        run: make test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    env: 
      NAME_DOCKER_IMAGE: "calculadoralambda"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4
      - name: "Build Lambda"
        run: docker build -t $NAME_DOCKER_IMAGE .
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-region: us-east-1
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
      # - name: "Login ECR"
      #   run : aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

